//
// PaymentvalidationAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire




public class PaymentvalidationAPI: APIBase {

    /**
     
     Submit payment validation for PayPal
     
     - parameter orderId: (query) Order Id returned from orders/POST
     - parameter payPalKey: (query) The PayPal key returned from the Mobile SDK
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func paymentvalidation(orderId orderId: String, payPalKey: String, completion: ((data: PaymentValidationResponse?, error: ErrorType?) -> Void)) {
        paymentvalidationWithRequestBuilder(orderId: orderId, payPalKey: payPalKey).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }



    /**
     
     Submit payment validation for PayPal
     
     - GET /paymentvalidation/
     - Submit payment validation for PayPal
     - examples: [{contentType=application/json, example={
  "IsValid" : true
}}]
     
     - parameter orderId: (query) Order Id returned from orders/POST
     - parameter payPalKey: (query) The PayPal key returned from the Mobile SDK

     - returns: RequestBuilder<PaymentValidationResponse> 
     */
    public class func paymentvalidationWithRequestBuilder(orderId orderId: String, payPalKey: String) -> RequestBuilder<PaymentValidationResponse> {
        let path = "/paymentvalidation/"
        let URLString = Gooten.API.ClientAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [
            "OrderId": orderId,
            "PayPalKey": payPalKey
        ]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<PaymentValidationResponse>.Type = Gooten.API.ClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: parameters, isBody: false)
    }


}


