//
// ProductpreviewAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire




public class ProductpreviewAPI: APIBase {

    /**
     
     Submit an image (or images) to be rendered into a product preview.
     
     - parameter productPreviewRequest: (body) Request detailing the operation needing completed
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func pOSTProductpreview(productPreviewRequest productPreviewRequest: ProductPreviewRequest, completion: ((data: ProductPreviewResponse?, error: ErrorType?) -> Void)) {
        pOSTProductpreviewWithRequestBuilder(productPreviewRequest: productPreviewRequest).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }



    /**
     
     Submit an image (or images) to be rendered into a product preview.
     
     - POST /productpreview/
     - Submit an image (or images) to be rendered into a product preview.
     - examples: [{contentType=application/json, example={
  "HadError" : true,
  "ErrorMessage" : "aeiou",
  "Url" : "aeiou"
}}]
     
     - parameter productPreviewRequest: (body) Request detailing the operation needing completed

     - returns: RequestBuilder<ProductPreviewResponse> 
     */
    public class func pOSTProductpreviewWithRequestBuilder(productPreviewRequest productPreviewRequest: ProductPreviewRequest) -> RequestBuilder<ProductPreviewResponse> {
        let path = "/productpreview/"
        let URLString = Gooten.API.ClientAPI.basePath + path
        
        let parameters = productPreviewRequest.encodeToJSON() as? [String:AnyObject]

        let requestBuilder: RequestBuilder<ProductPreviewResponse>.Type = Gooten.API.ClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: parameters, isBody: true)
    }


}


