//
// ShippriceestimateAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire




public class ShippriceestimateAPI: APIBase {

    /**
     
     Get a baseline ship price for an item
     
     - parameter productId: (query) Product ID
     - parameter countryCode: (query) Country Code it will be shipped to
     - parameter currencyCode: (query) Currency Code the estimate should be in. Defaults to USD.
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getShippriceestimate(productId productId: Int, countryCode: String, currencyCode: String?, completion: ((data: ShipEstimate?, error: ErrorType?) -> Void)) {
        getShippriceestimateWithRequestBuilder(productId: productId, countryCode: countryCode, currencyCode: currencyCode).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }



    /**
     
     Get a baseline ship price for an item
     
     - GET /shippriceestimate/
     - Price returned is an estimate which may or may not be realistically attainable.
     - examples: [{contentType=application/json, example={
  "VendorCountryCode" : "aeiou",
  "MaxPrice" : "",
  "EstShipDays" : 123456789,
  "MinPrice" : {
    "CurrencyCode" : "aeiou",
    "Price" : 123456789,
    "FormattedPrice" : "aeiou"
  },
  "CanShipExpedited" : true
}}]
     
     - parameter productId: (query) Product ID
     - parameter countryCode: (query) Country Code it will be shipped to
     - parameter currencyCode: (query) Currency Code the estimate should be in. Defaults to USD.

     - returns: RequestBuilder<ShipEstimate> 
     */
    public class func getShippriceestimateWithRequestBuilder(productId productId: Int, countryCode: String, currencyCode: String?) -> RequestBuilder<ShipEstimate> {
        let path = "/shippriceestimate/"
        let URLString = Gooten.API.ClientAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [
            "productId": productId,
            "countryCode": countryCode,
            "currencyCode": currencyCode
        ]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<ShipEstimate>.Type = Gooten.API.ClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: parameters, isBody: false)
    }


}


