//
// Address.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Address: JSONEncodable {

    public var city: String?
    public var countryCode: String?
    public var postalCode: String?
    public var stateOrProvinceCode: String?
    public var streetLines: [String]?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["city"] = self.city
        nillableDictionary["countryCode"] = self.countryCode
        nillableDictionary["postalCode"] = self.postalCode
        nillableDictionary["stateOrProvinceCode"] = self.stateOrProvinceCode
        nillableDictionary["streetLines"] = self.streetLines?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
