//
// ImageSizeVm.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ImageSizeVm: JSONEncodable {

    public var spaceId: String?
    public var width: Int?
    public var height: Int?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["spaceId"] = self.spaceId
        nillableDictionary["width"] = self.width
        nillableDictionary["height"] = self.height
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
