//
// Order.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Order: JSONEncodable {

    public var shipToAddress: ShipToAddress?
    public var items: [OrderItem]?
    public var payment: Payment?
    public var couponCode: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["shipToAddress"] = self.shipToAddress?.encodeToJSON()
        nillableDictionary["items"] = self.items?.encodeToJSON()
        nillableDictionary["payment"] = self.payment?.encodeToJSON()
        nillableDictionary["couponCode"] = self.couponCode
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
