//
// ProductPreviewRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ProductPreviewRequest: JSONEncodable {

    public var sku: String?
    public var template: String?
    public var images: [ProductPreviewImage]?
    /** Max height of the resultant image. Defaults to 500px */
    public var maxHeight: Int?
    /** Max width of the resultant image. Defaults to 500px */
    public var maxWidth: Int?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["sku"] = self.sku
        nillableDictionary["template"] = self.template
        nillableDictionary["images"] = self.images?.encodeToJSON()
        nillableDictionary["maxHeight"] = self.maxHeight
        nillableDictionary["maxWidth"] = self.maxWidth
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
