//
// SearchSubmittedOrder.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class SearchSubmittedOrder: JSONEncodable {

    public var id: String?
    public var niceId: String?
    /** Clients can submit an ID they use for the order here. */
    public var sourceId: String?
    public var items: [PostSubmittedItem]?
    public var total: ProductPriceInfo?
    public var shippingTotal: ProductPriceInfo?
    public var discountCode: String?
    public var discountAmount: ProductPriceInfo?
    /** An optional Map&lt;string,string&gt; of misc properties. */
    public var meta: Meta?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["niceId"] = self.niceId
        nillableDictionary["sourceId"] = self.sourceId
        nillableDictionary["items"] = self.items?.encodeToJSON()
        nillableDictionary["total"] = self.total?.encodeToJSON()
        nillableDictionary["shippingTotal"] = self.shippingTotal?.encodeToJSON()
        nillableDictionary["discountCode"] = self.discountCode
        nillableDictionary["discountAmount"] = self.discountAmount?.encodeToJSON()
        nillableDictionary["meta"] = self.meta?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
