//
// Country.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Country: JSONEncodable {

    public var name: String?
    public var code: String?
    public var isSupported: Bool?
    public var measurementCode: String?
    public var flagUrl: String?
    public var defaultCurrency: Currency?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["name"] = self.name
        nillableDictionary["code"] = self.code
        nillableDictionary["isSupported"] = self.isSupported
        nillableDictionary["measurementCode"] = self.measurementCode
        nillableDictionary["flagUrl"] = self.flagUrl
        nillableDictionary["defaultCurrency"] = self.defaultCurrency?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

