//
// OrderItemImage.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class OrderItemImage: JSONEncodable {

    public var url: String?
    public var index: Int?
    public var thumbnailUrl: String?
    public var manipCommand: String?
    public var spaceId: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["url"] = self.url
        nillableDictionary["index"] = self.index
        nillableDictionary["thumbnailUrl"] = self.thumbnailUrl
        nillableDictionary["manipCommand"] = self.manipCommand
        nillableDictionary["spaceId"] = self.spaceId
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

