//
// OrderItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class OrderItem: JSONEncodable {

    public var quantity: Int?
    public var SKU: String?
    public var shipCarrierMethodId: Int?
    public var images: [OrderItemImage]?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["quantity"] = self.quantity
        nillableDictionary["SKU"] = self.SKU
        nillableDictionary["shipCarrierMethodId"] = self.shipCarrierMethodId
        nillableDictionary["images"] = self.images?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

