//
// PostOrder.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class PostOrder: JSONEncodable {

    public var shipToAddress: ShipToAddress?
    public var billingAddress: ShipToAddress?
    public var items: [PostOrderItem]?
    public var payment: OrderPayment?
    /** Clients can submit an ID they use for the order here. */
    public var sourceId: String?
    /** Submit the order into PrePayment status. */
    public var isPreSubmit: Bool?
    public var couponCode: String?
    /** An optional Map&lt;string,string&gt; of misc properties. */
    public var meta: Meta?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["shipToAddress"] = self.shipToAddress?.encodeToJSON()
        nillableDictionary["billingAddress"] = self.billingAddress?.encodeToJSON()
        nillableDictionary["items"] = self.items?.encodeToJSON()
        nillableDictionary["payment"] = self.payment?.encodeToJSON()
        nillableDictionary["sourceId"] = self.sourceId
        nillableDictionary["isPreSubmit"] = self.isPreSubmit
        nillableDictionary["couponCode"] = self.couponCode
        nillableDictionary["meta"] = self.meta?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

