//
// PostSubmittedItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class PostSubmittedItem: JSONEncodable {

    public var sku: String?
    public var productId: Int?
    /** The type of product that was bought */
    public var product: String?
    public var quantity: Int?
    public var status: String?
    /** Deprecated. Use the Shipments array as this will be removed in a future release. */
    public var trackingNumber: String?
    /** Deprecated. Use the Shipments array as this will be removed in a future release. */
    public var trackingUrl: String?
    /** Deprecated. Use the Shipments array as this will be removed in a future release. */
    public var shipCarrierName: String?
    public var price: ProductPriceInfo?
    public var discountAmount: ProductPriceInfo?
    /** Partner&#39;s internal ID-- entirely optional */
    public var sourceId: String?
    /** An optional Map&lt;string,string&gt; of misc properties. */
    public var meta: Meta?
    public var shipments: [Shipment]?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["sku"] = self.sku
        nillableDictionary["productId"] = self.productId
        nillableDictionary["product"] = self.product
        nillableDictionary["quantity"] = self.quantity
        nillableDictionary["status"] = self.status
        nillableDictionary["trackingNumber"] = self.trackingNumber
        nillableDictionary["trackingUrl"] = self.trackingUrl
        nillableDictionary["shipCarrierName"] = self.shipCarrierName
        nillableDictionary["price"] = self.price?.encodeToJSON()
        nillableDictionary["discountAmount"] = self.discountAmount?.encodeToJSON()
        nillableDictionary["sourceId"] = self.sourceId
        nillableDictionary["meta"] = self.meta?.encodeToJSON()
        nillableDictionary["shipments"] = self.shipments?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

