//
// PostOrderItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class PostOrderItem: JSONEncodable {

    public var quantity: Int?
    public var SKU: String?
    public var shipCarrierMethodId: Int?
    /** If one does not want to pass a ShipCarrierMethodId of a specific shipping method, one can instead pass &#39;Standard&#39;, &#39;Overnight&#39;, or &#39;Expedited&#39; here. */
    public var shipType: String?
    public var images: [Image]?
    /** An optional place to pass in an ID for the OrderItem. */
    public var sourceId: String?
    /** An optional Map&lt;string,string&gt; of misc properties. */
    public var meta: Meta?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["quantity"] = self.quantity
        nillableDictionary["SKU"] = self.SKU
        nillableDictionary["shipCarrierMethodId"] = self.shipCarrierMethodId
        nillableDictionary["shipType"] = self.shipType
        nillableDictionary["images"] = self.images?.encodeToJSON()
        nillableDictionary["sourceId"] = self.sourceId
        nillableDictionary["meta"] = self.meta?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
