//
// PostSubmittedOrder.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class PostSubmittedOrder: JSONEncodable {

    /** The unique ID we use within our system. */
    public var id: String?
    /** A short, non-unique ID that is optionally used for customer service. */
    public var niceId: String?
    /** Partner&#39;s internal ID-- entirely optional */
    public var souceId: String?
    public var items: [PostSubmittedItem]?
    public var total: ProductPriceInfo?
    public var shippingTotal: ProductPriceInfo?
    public var discountAmount: ProductPriceInfo?
    public var discountCode: String?
    public var billingAddress: ShipToAddress?
    public var shippingAddress: ShipToAddress?
    /** An optional Map&lt;string,string&gt; of misc properties. */
    public var meta: Meta?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["niceId"] = self.niceId
        nillableDictionary["souceId"] = self.souceId
        nillableDictionary["items"] = self.items?.encodeToJSON()
        nillableDictionary["total"] = self.total?.encodeToJSON()
        nillableDictionary["shippingTotal"] = self.shippingTotal?.encodeToJSON()
        nillableDictionary["discountAmount"] = self.discountAmount?.encodeToJSON()
        nillableDictionary["discountCode"] = self.discountCode
        nillableDictionary["billingAddress"] = self.billingAddress?.encodeToJSON()
        nillableDictionary["shippingAddress"] = self.shippingAddress?.encodeToJSON()
        nillableDictionary["meta"] = self.meta?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
