//
// PreconfiguredProduct.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class PreconfiguredProduct: JSONEncodable {

    /** A sku that uniquely identifies the preconfigured product. */
    public var sku: String?
    public var name: String?
    public var description: String?
    public var price: ProductPriceInfo?
    /** The item[s] that constitue the product. */
    public var items: [PreconfiguredItem]?
    /** Product images. Can contain large and small images for web, mobile, etc */
    public var images: [PreconfiguredProductImage]?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["sku"] = self.sku
        nillableDictionary["name"] = self.name
        nillableDictionary["description"] = self.description
        nillableDictionary["price"] = self.price?.encodeToJSON()
        nillableDictionary["items"] = self.items?.encodeToJSON()
        nillableDictionary["images"] = self.images?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

