//
// PreconfiguredItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class PreconfiguredItem: JSONEncodable {

    /** The ID of the product this item references. */
    public var productId: Int?
    /** The sku of the product variant this item references. */
    public var productVariantSku: String?
    public var preconfigurations: [Preconfiguration]?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["productId"] = self.productId
        nillableDictionary["productVariantSku"] = self.productVariantSku
        nillableDictionary["preconfigurations"] = self.preconfigurations?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

