//
// ProductBuildOption.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ProductBuildOption: JSONEncodable {

    public var name: String?
    public var imageUrl: String?
    public var isDefault: Bool?
    public var category: String?
    public var isPartnerSpecific: Bool?
    public var spaces: [ProductBuildInfoSpace]?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["name"] = self.name
        nillableDictionary["imageUrl"] = self.imageUrl
        nillableDictionary["isDefault"] = self.isDefault
        nillableDictionary["category"] = self.category
        nillableDictionary["isPartnerSpecific"] = self.isPartnerSpecific
        nillableDictionary["spaces"] = self.spaces?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

