//
// ProductBuildInfoSpace.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ProductBuildInfoSpace: JSONEncodable {

    public var id: String?
    public var description: String?
    public var index: Int?
    public var defaultRotation: Int?
    public var layers: [ProductBuildInfo]?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["description"] = self.description
        nillableDictionary["index"] = self.index
        nillableDictionary["defaultRotation"] = self.defaultRotation
        nillableDictionary["layers"] = self.layers?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

