//
// ProductVariantResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ProductVariantResponse: JSONEncodable {

    public var productVariants: [ProductVariant]?
    public var options: [ProductOptionList]?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["productVariants"] = self.productVariants?.encodeToJSON()
        nillableDictionary["options"] = self.options?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

