//
// ProductInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ProductInfo: JSONEncodable {

    public var contentType: String?
    public var content: [String]?
    public var key: String?
    /** The suggested ordering of the content about the product. */
    public var index: Int?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["contentType"] = self.contentType
        nillableDictionary["content"] = self.content?.encodeToJSON()
        nillableDictionary["key"] = self.key
        nillableDictionary["index"] = self.index
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

