//
// ProductVariant.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ProductVariant: JSONEncodable {

    public var sku: String?
    public var maxImages: Int?
    public var hasTemplates: Bool?
    public var options: [ProductOption]?
    public var priceInfo: ProductPriceInfo?
    public var partnerPriceInfo: ProductPriceInfo?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["sku"] = self.sku
        nillableDictionary["maxImages"] = self.maxImages
        nillableDictionary["hasTemplates"] = self.hasTemplates
        nillableDictionary["options"] = self.options?.encodeToJSON()
        nillableDictionary["priceInfo"] = self.priceInfo?.encodeToJSON()
        nillableDictionary["partnerPriceInfo"] = self.partnerPriceInfo?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
