//
// Shipment.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Shipment: JSONEncodable {

    public var trackingNumber: String?
    public var trackingUrl: String?
    public var shipCarrierName: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["trackingNumber"] = self.trackingNumber
        nillableDictionary["trackingUrl"] = self.trackingUrl
        nillableDictionary["shipCarrierName"] = self.shipCarrierName
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

