//
// ShipOption.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ShipOption: JSONEncodable {

    /** The ID that can be passed into the /orders POST endpoing as ShipCarrierMethodId to specify an item&#39;s shipping method. */
    public var id: Int?
    public var methodType: String?
    public var methodId: Int?
    public var name: String?
    public var carrierName: String?
    public var carrierLogoUrl: String?
    public var price: ShipPrice?
    public var partnerPrice: ShipPrice?
    public var estBusinessDaysTilDelivery: Int?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["methodType"] = self.methodType
        nillableDictionary["methodId"] = self.methodId
        nillableDictionary["name"] = self.name
        nillableDictionary["carrierName"] = self.carrierName
        nillableDictionary["carrierLogoUrl"] = self.carrierLogoUrl
        nillableDictionary["price"] = self.price?.encodeToJSON()
        nillableDictionary["partnerPrice"] = self.partnerPrice?.encodeToJSON()
        nillableDictionary["estBusinessDaysTilDelivery"] = self.estBusinessDaysTilDelivery
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
