//
// ShipEstimate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ShipEstimate: JSONEncodable {

    public var minPrice: ShipPrice?
    public var maxPrice: ShipPrice?
    public var vendorCountryCode: String?
    public var canShipExpedited: Bool?
    public var estShipDays: Int?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["minPrice"] = self.minPrice?.encodeToJSON()
        nillableDictionary["maxPrice"] = self.maxPrice?.encodeToJSON()
        nillableDictionary["vendorCountryCode"] = self.vendorCountryCode
        nillableDictionary["canShipExpedited"] = self.canShipExpedited
        nillableDictionary["estShipDays"] = self.estShipDays
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

