//
// ShipToAddress.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ShipToAddress: JSONEncodable {

    public var firstName: String?
    public var lastName: String?
    public var line1: String?
    public var line2: String?
    public var city: String?
    public var state: String?
    public var countryCode: String?
    public var postalCode: String?
    public var isBusinessAddress: Bool?
    public var phone: String?
    public var email: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["firstName"] = self.firstName
        nillableDictionary["lastName"] = self.lastName
        nillableDictionary["line1"] = self.line1
        nillableDictionary["line2"] = self.line2
        nillableDictionary["city"] = self.city
        nillableDictionary["state"] = self.state
        nillableDictionary["countryCode"] = self.countryCode
        nillableDictionary["postalCode"] = self.postalCode
        nillableDictionary["isBusinessAddress"] = self.isBusinessAddress
        nillableDictionary["phone"] = self.phone
        nillableDictionary["email"] = self.email
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

