//
// UserInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class UserInfo: JSONEncodable {

    public var languageCode: String?
    public var countryCode: String?
    public var countryName: String?
    public var currencyName: String?
    public var currencyCode: String?
    public var currencyFormat: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["languageCode"] = self.languageCode
        nillableDictionary["countryCode"] = self.countryCode
        nillableDictionary["countryName"] = self.countryName
        nillableDictionary["currencyName"] = self.currencyName
        nillableDictionary["currencyCode"] = self.currencyCode
        nillableDictionary["currencyFormat"] = self.currencyFormat
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

