//
// ValidationFailure.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ValidationFailure: JSONEncodable {

    public var propertyName: String?
    public var errorMessage: String?
    public var attemptedValue: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["propertyName"] = self.propertyName
        nillableDictionary["errorMessage"] = self.errorMessage
        nillableDictionary["attemptedValue"] = self.attemptedValue
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
