//
// ImagesAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class ImagesAPI: APIBase {
    /**
     
     POSTs files to a temporary store
     
     - parameter images: (form) Form/multipart file post
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func postImages(images images: NSURL, completion: ((data: FileResult?, error: ErrorType?) -> Void)) {
        postImagesWithRequestBuilder(images: images).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     POSTs files to a temporary store
     
     - POST /images/
     - POSTs files to a temporary store
     - examples: [{contentType=application/json, example={
  "Price" : [ {
    "ManipCommand" : "aeiou",
    "ThumbnailUrl" : "aeiou",
    "SpaceId" : "aeiou",
    "Index" : 123456789,
    "Url" : "aeiou"
  } ]
}}]
     
     - parameter images: (form) Form/multipart file post

     - returns: RequestBuilder<FileResult> 
     */
    public class func postImagesWithRequestBuilder(images images: NSURL) -> RequestBuilder<FileResult> {
        let path = "/images/"
        let URLString = SwaggerClientAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [
            "Images": images
        ]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<FileResult>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: parameters, isBody: false)
    }

}
