//
// OrderstatusAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class OrderstatusAPI: APIBase {
    /**
     
     Update an order status
     
     - parameter id: (query) Order Id
     - parameter orderStatusName: (query) Order status name for update
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func pOSTOrderstatus(id id: String, orderStatusName: String, completion: ((data: OrderStatusUpdateResult?, error: ErrorType?) -> Void)) {
        pOSTOrderstatusWithRequestBuilder(id: id, orderStatusName: orderStatusName).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     Update an order status
     
     - POST /orderstatus/
     - Update status of each order item.
     - examples: [{contentType=application/json, example={
  "HadError" : true
}}]
     
     - parameter id: (query) Order Id
     - parameter orderStatusName: (query) Order status name for update

     - returns: RequestBuilder<OrderStatusUpdateResult> 
     */
    public class func pOSTOrderstatusWithRequestBuilder(id id: String, orderStatusName: String) -> RequestBuilder<OrderStatusUpdateResult> {
        let path = "/orderstatus/"
        let URLString = SwaggerClientAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [
            "id": id,
            "orderStatusName": orderStatusName
        ]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<OrderStatusUpdateResult>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: parameters, isBody: false)
    }

}
