//
// ProducttemplatesAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class ProducttemplatesAPI: APIBase {
    /**
     
     Get a list of product templates
     
     - parameter sku: (query) Productvariant sku.
     - parameter languageCode: (query) Two-character language code, defaults to \&quot;en\&quot; (english)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getProducttemplates(sku sku: String, languageCode: String?, completion: ((data: ProductBuildInfoResponse?, error: ErrorType?) -> Void)) {
        getProducttemplatesWithRequestBuilder(sku: sku, languageCode: languageCode).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     Get a list of product templates
     
     - GET /producttemplates/
     - Get a list of product templates.
     - examples: [{contentType=application/json, example={
  "Options" : [ {
    "IsDefault" : true,
    "Category" : "aeiou",
    "Spaces" : [ {
      "Description" : "aeiou",
      "Index" : 123456789,
      "Id" : "aeiou",
      "DefaultRotation" : 123456789,
      "Layers" : [ {
        "BackgroundImageUrl" : "aeiou",
        "FontVAlighment" : "aeiou",
        "Description" : "aeiou",
        "Color" : "aeiou",
        "OverlayImageUrl" : "aeiou",
        "FontHAlignment" : "aeiou",
        "DefaultText" : "aeiou",
        "Type" : "aeiou",
        "ZIndex" : 123456789,
        "FontSize" : "aeiou",
        "Y1" : 123456789,
        "FontName" : "aeiou",
        "X1" : 123456789,
        "Y2" : 123456789,
        "X2" : 123456789,
        "Id" : "aeiou"
      } ]
    } ],
    "ImageUrl" : "aeiou",
    "IsPartnerSpecific" : true,
    "Name" : "aeiou"
  } ]
}}]
     
     - parameter sku: (query) Productvariant sku.
     - parameter languageCode: (query) Two-character language code, defaults to \&quot;en\&quot; (english)

     - returns: RequestBuilder<ProductBuildInfoResponse> 
     */
    public class func getProducttemplatesWithRequestBuilder(sku sku: String, languageCode: String?) -> RequestBuilder<ProductBuildInfoResponse> {
        let path = "/producttemplates/"
        let URLString = SwaggerClientAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [
            "sku": sku,
            "languageCode": languageCode
        ]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<ProductBuildInfoResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: parameters, isBody: false)
    }

}
